### ISSUE TITLE
project not maintained

### ISSUE THREAD

**Issue by domdinicola** [nigma/django-easy-pdf#79]
@nigma @msaizar @metakermit are you guys interested in supporting this project?
Many people are waiting for a new version supporting django 3.0.
I may be interested to give continuity to this, feel free to give me access here and on pypi (dom.dinicola)

**Comment by olksndrdevhub** [comment]
Check my fresh [fork](https://github.com/olksndrdevhub/django-easy-pdf), maybe it`s help you

**Comment by domdinicola** [comment]
@olksndrdevhub do you release packages on pypi?

**Comment by olksndrdevhub** [comment]
> @olksndrdevhub do you release packages on pypi?

No, I only today make fork
but you can put it in your requirements.txt as
-e git://github.com/olksndrdevhub/django-easy-pdf.git#egg=django-easy-pdf

**Comment by domdinicola** [comment]
thanks.. but I prefere to have stable packages released, where I can pin version and be sure what I'm running.
Thanks for forking hope you can do some work and maybe release the package with a new (similar) way.
In that case I would be very happy to support you!

**Comment by domdinicola** [comment]
> > @olksndrdevhub do you release packages on pypi?
> 
> No, I only today make fork
> but you can put it in your requirements.txt as
> -e git://github.com/olksndrdevhub/django-easy-pdf.git#egg=django-easy-pdf

thanks.. but I prefere to have stable packages released, where I can pin version and be sure what I'm running.
Thanks for forking hope you can do some work and maybe release the package with a new (similar) way.
In that case I would be very happy to support you!

**Comment by olksndrdevhub** [comment]
> > > @olksndrdevhub do you release packages on pypi?
> > 
> > No, I only today make fork
> > but you can put it in your requirements.txt as
> > -e git://github.com/olksndrdevhub/django-easy-pdf.git#egg=django-easy-pdf
> 
> thanks.. but I prefere to have stable packages released, where I can pin version and be sure what I'm running.
> Thanks for forking hope you can do some work and maybe release the package with a new (similar) way.
> In that case I would be very happy to support you!

Yeah, maybe I will think about release at Pypi

**Comment by olksndrdevhub** [comment]
@domdinicola hi there!
I release my fork at PyPI now!
Check it, [here](https://pypi.org/project/django-easy-pdf3/).
It's perfectly work in my project, with Django 3.0.* and Wagtail 2.11.3, I hope it's will work for you too.

**Comment by domdinicola** [comment]
Thanks so much!

**Comment by openHBP** [comment]
Yesssss thanks a lot for this great job! Fed up with errors like:

- ImportError: cannot import name 'urlquote' from 'django.utils.http'
- ModuleNotFoundError: No module named 'django.utils.six'

**Comment by olksndrdevhub** [comment]
@openHBP please, check my fork, it must work pretty well
[django-easy-pdf3](https://github.com/olksndrdevhub/django-easy-pdf3)
pypi: [django-easy-pdf3](https://pypi.org/project/django-easy-pdf3/)

**Comment by openHBP** [comment]
That's what I did and it works perfect! Thanks :-)

**Comment by gdvalderrama** [comment]
There are a lot of forks for this project, but none was working for me: I needed Django 3+ and static images to work way better (base64 encoding was NOT working).
I just changed to https://github.com/fdemmer/django-weasyprint very easily and painlessly, just leaving it as a suggestion for other people.
